version: "3"

services:
  db:
    image: mysql:5.7.22
    restart: always
    container_name: mysql-container
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: a1b2V4d
      MYSQL_DATABASE: gin_app
  backend:
    build:
      context: . 
      dockerfile: ./docker/go/Dockerfile
    container_name: golang-container
    ports:
      - 8080:8080
    volumes:
      - ./app:/go/src/app
    working_dir: /go/src/app
    tty: true
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile
    container_name: vue-container
    volumes:
      - ./front:/app
    working_dir: /app
    ports:
      - 9000:80
    tty: true
