version: "3"

services:
  db:
    image: mysql:5.7.22
    restart: always
    container_name: mysql-container
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: a1b2V4d
  web:
    build:
      context: . 
      dockerfile: ./docker/go/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/go/src/app
    working_dir: /go/src/app
    tty: true
    depends_on:
      - db

